### PR TITLE
Log when a process is killed [Fixes #2]

### PR DESCRIPTION
**Pull request by robrwo**

### CODE REVIEW

**Comment by robrwo** [comment]
Thank you. I'll keep an eye out for when it's released.

**Comment by audreyt** [comment]
It is now released. :-) Thank you! :rainbow:

**Comment by robrwo** [comment]
Has it been packaged properly? When I install it from CPAN, I get the error
```
Can't locate inc/Module/Package.pm in @INC
```

**Comment by audreyt** [comment]
Thanks for the catch — re-packaged and re-uploaded as 0.08.

**Pull request merged**
